### ISSUE TITLE
첫번째 페이지 메인 캐로셀 구현

### ISSUE THREAD

**Issue by Hjname** [wooritech/woori-camp-mission-01#6]
헤더 하단에 위치한 캐러셀 작성 착수

- html, css를 사용하여 구성후 js를 사용해 움직임 구현
- [ ] #8 슬라이드 이미지 구현
- [ ] #9 슬라이드 구현
- [x] #10

**Comment by Hjname** [comment]
- [] #8 캐로셀 이미지 구현
- [] #9 슬라이드 구현
- [] #10 슬라이드 자동화

**Comment by Malloc72P** [comment]
`- [ ]`이런식으로 작성해야 태스크로 등록됩니다! 대괄호 사이에 공백이 없네요

**Comment by Hjname** [comment]
- [ ] #8 캐로셀 이미지 구현
- [ ] #9 슬라이드 구현
- [ ] #10 슬라이드 자동화

**Comment by Hjname** [comment]
작성한 태스크를 이슈로 만드는건 이전과 동일하게 이슈 작성을 하면 될까요?

**Comment by Malloc72P** [comment]
> 작성한 태스크를 이슈로 만드는건 이전과 동일하게 이슈 작성을 하면 될까요?

직접 만들어도 좋고, 아까 오프라인으로 알려드린 것 처럼, `convert to issue` 버튼으로 이슈 생성해도 됩니다

근데 `convert to issue` 버튼은 코멘트에선 안되고 이슈 본문에서만 되네요 ㅎㅎ
